services:
  directory-service:
    container_name: tasks-directory-service
    build:
      context: ./DirectoryService
      dockerfile: src/DirectoryService.Web/Dockerfile
    ports:
      - "9001:9001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:9001
    restart: always
  seq:
    image: datalust/seq:latest
    container_name: tasks-seq
    ports:
      - "5348:80"          # Веб-интерфейс Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin  # см. ниже
    volumes:
      - seq-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  seq-data: