services:
  directory-service:
    build:
      context: ./DirectoryService
      dockerfile: src/DirectoryService.Web/Dockerfile
    container_name: tasks-directory-service
    ports:
      - "5052:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: tasks-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=directory_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d directory_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tasks-pgadmin
    entrypoint:
      - /bin/sh
      - -c
      - |
        cp /pgpass /var/lib/pgadmin/.pgpass
        chown 5050:5050 /var/lib/pgadmin/.pgpass
        chmod 600 /var/lib/pgadmin/.pgpass
        exec /entrypoint.sh
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.dev
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_REPLACE_SERVERS_ON_STARTUP=True
      - PGPASS_FILE=/pgpass
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpass:/pgpass:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: tasks-seq
    ports:
      - "5348:80"          # Веб-интерфейс Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    volumes:
      - seq-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:
  pgadmin-data:
  seq-data:
