// <auto-generated />
using System;
using DirectoryService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DirectoryService.Infrastructure.Postgres.Migrations;

[DbContext(typeof(DirectoryDbContext))]
[Migration("20260806082157_AddRelationIdsAndDepartmentHierarchy")]
partial class AddRelationIdsAndDepartmentHierarchy
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("DirectoryService.Domain.Entity.Department", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTime?>("DeletionDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("deletion_date");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean")
                    .HasColumnName("is_deleted");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("uuid")
                    .HasColumnName("parent_id");

                b.Property<string>("Path")
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)")
                    .HasColumnName("path");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.HasIndex("ParentId");

                b.HasIndex("Path");

                b.ToTable("departments", (string)null);
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.DepartmentLocation", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uuid")
                    .HasColumnName("department_id");

                b.Property<Guid>("LocationId")
                    .HasColumnType("uuid")
                    .HasColumnName("location_id");

                b.HasKey("Id");

                b.HasIndex("LocationId");

                b.HasIndex("DepartmentId", "LocationId")
                    .IsUnique();

                b.ToTable("department_locations", (string)null);
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.DepartmentPosition", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("DepartmentId")
                    .HasColumnType("uuid")
                    .HasColumnName("department_id");

                b.Property<Guid>("PositionId")
                    .HasColumnType("uuid")
                    .HasColumnName("position_id");

                b.HasKey("Id");

                b.HasIndex("PositionId");

                b.HasIndex("DepartmentId", "PositionId")
                    .IsUnique();

                b.ToTable("department_positions", (string)null);
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.Location", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTime?>("DeletionDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("deletion_date");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean")
                    .HasColumnName("is_deleted");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.ToTable("locations", (string)null);
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.Position", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTime?>("DeletionDate")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("deletion_date");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean")
                    .HasColumnName("is_deleted");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.HasKey("Id");

                b.HasIndex("IsDeleted");

                b.ToTable("positions", (string)null);
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.Department", b =>
            {
                b.HasOne("DirectoryService.Domain.Entity.Department", null)
                    .WithMany()
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.OwnsOne("DirectoryService.Domain.ValueObjects.DepartmentName", "Name", b1 =>
                    {
                        b1.Property<Guid>("DepartmentId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(150)
                            .HasColumnType("character varying(150)")
                            .HasColumnName("name");

                        b1.HasKey("DepartmentId");

                        b1.ToTable("departments");

                        b1.WithOwner()
                            .HasForeignKey("DepartmentId");
                    });

                b.OwnsOne("DirectoryService.Domain.ValueObjects.Depth", "Depth", b1 =>
                    {
                        b1.Property<Guid>("DepartmentId")
                            .HasColumnType("uuid");

                        b1.Property<short>("Value")
                            .HasColumnType("smallint")
                            .HasColumnName("depth");

                        b1.HasKey("DepartmentId");

                        b1.ToTable("departments");

                        b1.WithOwner()
                            .HasForeignKey("DepartmentId");
                    });

                b.OwnsOne("DirectoryService.Domain.ValueObjects.Identifier", "Identifier", b1 =>
                    {
                        b1.Property<Guid>("DepartmentId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(150)
                            .HasColumnType("character varying(150)")
                            .HasColumnName("identifier");

                        b1.HasKey("DepartmentId");

                        b1.HasIndex("Value")
                            .IsUnique();

                        b1.ToTable("departments");

                        b1.WithOwner()
                            .HasForeignKey("DepartmentId");
                    });

                b.Navigation("Depth")
                    .IsRequired();

                b.Navigation("Identifier")
                    .IsRequired();

                b.Navigation("Name")
                    .IsRequired();
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.DepartmentLocation", b =>
            {
                b.HasOne("DirectoryService.Domain.Entity.Department", null)
                    .WithMany("Locations")
                    .HasForeignKey("DepartmentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DirectoryService.Domain.Entity.Location", null)
                    .WithMany("Departments")
                    .HasForeignKey("LocationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.DepartmentPosition", b =>
            {
                b.HasOne("DirectoryService.Domain.Entity.Department", null)
                    .WithMany("Positions")
                    .HasForeignKey("DepartmentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("DirectoryService.Domain.Entity.Position", null)
                    .WithMany("Departments")
                    .HasForeignKey("PositionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.Location", b =>
            {
                b.OwnsOne("DirectoryService.Domain.ValueObjects.Address", "Address", b1 =>
                    {
                        b1.Property<Guid>("LocationId")
                            .HasColumnType("uuid");

                        b1.Property<string>("City")
                            .HasMaxLength(100)
                            .HasColumnType("character varying(100)")
                            .HasColumnName("city");

                        b1.Property<string>("Country")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("character varying(100)")
                            .HasColumnName("country");

                        b1.Property<string>("PostalCode")
                            .HasMaxLength(20)
                            .HasColumnType("character varying(20)")
                            .HasColumnName("postal_code");

                        b1.Property<string>("Region")
                            .HasMaxLength(100)
                            .HasColumnType("character varying(100)")
                            .HasColumnName("region");

                        b1.Property<string>("Street")
                            .HasMaxLength(100)
                            .HasColumnType("character varying(100)")
                            .HasColumnName("street");

                        b1.HasKey("LocationId");

                        b1.ToTable("locations");

                        b1.WithOwner()
                            .HasForeignKey("LocationId");
                    });

                b.OwnsOne("DirectoryService.Domain.ValueObjects.IANACode", "Timezone", b1 =>
                    {
                        b1.Property<Guid>("LocationId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(35)
                            .HasColumnType("character varying(35)")
                            .HasColumnName("timezone");

                        b1.HasKey("LocationId");

                        b1.ToTable("locations");

                        b1.WithOwner()
                            .HasForeignKey("LocationId");
                    });

                b.OwnsOne("DirectoryService.Domain.ValueObjects.LocationName", "Name", b1 =>
                    {
                        b1.Property<Guid>("LocationId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(120)
                            .HasColumnType("character varying(120)")
                            .HasColumnName("name");

                        b1.HasKey("LocationId");

                        b1.ToTable("locations");

                        b1.WithOwner()
                            .HasForeignKey("LocationId");
                    });

                b.Navigation("Address")
                    .IsRequired();

                b.Navigation("Name")
                    .IsRequired();

                b.Navigation("Timezone")
                    .IsRequired();
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.Position", b =>
            {
                b.OwnsOne("DirectoryService.Domain.ValueObjects.Description", "Description", b1 =>
                    {
                        b1.Property<Guid>("PositionId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .HasMaxLength(1000)
                            .HasColumnType("character varying(1000)")
                            .HasColumnName("description");

                        b1.HasKey("PositionId");

                        b1.ToTable("positions");

                        b1.WithOwner()
                            .HasForeignKey("PositionId");
                    });

                b.OwnsOne("DirectoryService.Domain.ValueObjects.PositionName", "Name", b1 =>
                    {
                        b1.Property<Guid>("PositionId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("character varying(100)")
                            .HasColumnName("name");

                        b1.HasKey("PositionId");

                        b1.ToTable("positions");

                        b1.WithOwner()
                            .HasForeignKey("PositionId");
                    });

                b.Navigation("Description")
                    .IsRequired();

                b.Navigation("Name")
                    .IsRequired();
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.Department", b =>
            {
                b.Navigation("Locations");

                b.Navigation("Positions");
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.Location", b =>
            {
                b.Navigation("Departments");
            });

        modelBuilder.Entity("DirectoryService.Domain.Entity.Position", b =>
            {
                b.Navigation("Departments");
            });
#pragma warning restore 612, 618
    }
}
